name = zero7even_economy
description = Zero7even Coins, Shards, and Experience Money integration
author = Zero7even
depends = zero7even_core, zero7even_bridge, zero7even_identity, zero7even_permissions
